// <auto-generated />
namespace EmployeeManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201907031402189_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
